db.createCollection("cities");
db.cities.insertMany([
	{"city":"Tokyo",
	"population":13960000,
	"continent":"Asia",
	"country":"Japan",
	"known_for":["technology",
		"finance",
		"anime culture"],
	"coordinates":{"lat":35.6762,
		"long":139.6503},
	"timezone":"Asia/Tokyo"},
	{"city":"Paris",
		"population":2161000,
		"continent":"Europe",
		"country":"France",
		"known_for":["Eiffel Tower",
			"fashion",
			"art"],
		"coordinates":{"lat":48.8566,
			"long":2.3522},
		"timezone":"Europe/Paris"},
	{"city":"Berlin",
		"population":3671000,
		"continent":"Europe",
		"country":"Germany",
		"known_for":["Brandenburg Gate",
			"history",
			"startups"],
		"coordinates":{"lat":52.52,
			"long":13.405},
		"timezone":"Europe/Berlin"},
	{"city":"London",
		"population":8982000,
		"continent":"Europe",
		"country":"United Kingdom",
		"known_for":["Big Ben",
			"finance",
			"royalty"],
		"coordinates":{"lat":51.5074,
			"long":-0.1278},
		"timezone":"Europe/London"},
	{"city":"Madrid",
		"population":3266000,
		"continent":"Europe",
		"country":"Spain",
		"known_for":["royal palace",
			"football",
			"art museums"],
		"coordinates":{"lat":40.4168,
			"long":-3.7038},
		"timezone":"Europe/Madrid"},
	{"city":"Rome",
		"population":2873000,
		"continent":"Europe",
		"country":"Italy",
		"known_for":["Colosseum",
			"Roman history",
			"Vatican proximity"],
		"coordinates":{"lat":41.9028,
			"long":12.4964},
		"timezone":"Europe/Rome"},
	{"city":"Vienna",
		"population":1980000,
		"continent":"Europe",
		"country":"Austria",
		"known_for":["classical music",
			"imperial palaces",
			"coffee houses"],
		"coordinates":{"lat":48.2082,
			"long":16.3738},
		"timezone":"Europe/Vienna"},
	{"city":"Prague",
		"population":1310000,
		"continent":"Europe",
		"country":"Czech Republic",
		"known_for":["Charles Bridge",
			"old town",
			"architecture"],
		"coordinates":{"lat":50.0755,
			"long":14.4378},
		"timezone":"Europe/Prague"},
	{"city":"Warsaw",
		"population":1794000,
		"continent":"Europe",
		"country":"Poland",
		"known_for":["rebuilt old town",
			"history",
			"government"],
		"coordinates":{"lat":52.2297,
			"long":21.0122},
		"timezone":"Europe/Warsaw"},
	{"city":"Amsterdam",
		"population":905000,
		"continent":"Europe",
		"country":"Netherlands",
		"known_for":["canals",
			"cycling",
			"museums"],
		"coordinates":{"lat":52.3676,
			"long":4.9041},
		"timezone":"Europe/Amsterdam"},
	{"city":"Brussels",
		"population":185000,
		"continent":"Europe",
		"country":"Belgium",
		"known_for":["EU institutions",
			"Grand Place",
			"chocolate"],
		"coordinates":{"lat":50.8503,
			"long":4.3517},
		"timezone":"Europe/Brussels"},
	{"city":"Copenhagen",
		"population":653000,
		"continent":"Europe",
		"country":"Denmark",
		"known_for":["design",
			"cycling",
			"Nyhavn"],
		"coordinates":{"lat":55.6761,
			"long":12.5683},
		"timezone":"Europe/Copenhagen"},
	{"city":"Stockholm",
		"population":975000,
		"continent":"Europe",
		"country":"Sweden",
		"known_for":["archipelago",
			"innovation",
			"Gamla Stan"],
		"coordinates":{"lat":59.3293,
			"long":18.0686},
		"timezone":"Europe/Stockholm"},
	{"city":"Oslo",
		"population":709000,
		"continent":"Europe",
		"country":"Norway",
		"known_for":["fjord access",
			"maritime culture",
			"sustainability"],
		"coordinates":{"lat":59.9139,
			"long":10.7522},
		"timezone":"Europe/Oslo"},
	{"city":"Helsinki",
		"population":658000,
		"continent":"Europe",
		"country":"Finland",
		"known_for":["design",
			"saunas",
			"Baltic coast"],
		"coordinates":{"lat":60.1699,
			"long":24.9384},
		"timezone":"Europe/Helsinki"},
	{"city":"Lisbon",
		"population":545000,
		"continent":"Europe",
		"country":"Portugal",
		"known_for":["tramways",
			"fado",
			"hills"],
		"coordinates":{"lat":38.7223,
			"long":-9.1393},
		"timezone":"Europe/Lisbon"},
	{"city":"Dublin",
		"population":592000,
		"continent":"Europe",
		"country":"Ireland",
		"known_for":["literature",
			"pub culture",
			"tech hub"],
		"coordinates":{"lat":53.3498,
			"long":-6.2603},
		"timezone":"Europe/Dublin"},
	{"city":"Athens",
		"population":664000,
		"continent":"Europe",
		"country":"Greece",
		"known_for":["Acropolis",
			"philosophy",
			"ancient history"],
		"coordinates":{"lat":37.9838,
			"long":23.7275},
		"timezone":"Europe/Athens"},
	{"city":"Budapest",
		"population":1752000,
		"continent":"Europe",
		"country":"Hungary",
		"known_for":["Danube",
			"thermal baths",
			"Parliament"],
		"coordinates":{"lat":47.4979,
			"long":19.0402},
		"timezone":"Europe/Budapest"},
	{"city":"Bucharest",
		"population":1716000,
		"continent":"Europe",
		"country":"Romania",
		"known_for":["Parliament Palace",
			"history",
			"boulevards"],
		"coordinates":{"lat":44.4268,
			"long":26.1025},
		"timezone":"Europe/Bucharest"},
	{"city":"Washington, D.C.",
		"population":712000,
		"continent":"North America",
		"country":"United States",
		"known_for":["White House",
			"government",
			"Smithsonian"],
		"coordinates":{"lat":38.9072,
			"long":-77.0369},
		"timezone":"America/New_York"},
	{"city":"Ottawa",
		"population":1017000,
		"continent":"North America",
		"country":"Canada",
		"known_for":["Parliament Hill",
			"Rideau Canal",
			"government"],
		"coordinates":{"lat":45.4215,
			"long":-75.6972},
		"timezone":"America/Toronto"},
	{"city":"Mexico City",
		"population":9200000,
		"continent":"North America",
		"country":"Mexico",
		"known_for":["Aztec history",
			"food",
			"large metro"],
		"coordinates":{"lat":19.4326,
			"long":-99.1332},
		"timezone":"America/Mexico_City"},
	{"city":"Brasilia",
		"population":3094000,
		"continent":"South America",
		"country":"Brazil",
		"known_for":["modernist architecture",
			"planned city",
			"government"],
		"coordinates":{"lat":-15.7939,
			"long":-47.8828},
		"timezone":"America/Sao_Paulo"},
	{"city":"Buenos Aires",
		"population":3075000,
		"continent":"South America",
		"country":"Argentina",
		"known_for":["tango",
			"culture",
			"European architecture"],
		"coordinates":{"lat":-34.6037,
			"long":-58.3816},
		"timezone":"America/Argentina/Buenos_Aires"},
	{"city":"Tokyo",
		"population":13960000,
		"continent":"Asia",
		"country":"Japan",
		"known_for":["technology",
			"finance",
			"anime culture"],
		"coordinates":{"lat":35.6762,
			"long":139.6503},
		"timezone":"Asia/Tokyo"},
	{"city":"Beijing",
		"population":21890000,
		"continent":"Asia",
		"country":"China",
		"known_for":["Forbidden City",
			"politics",
			"history"],
		"coordinates":{"lat":39.9042,
			"long":116.4074},
		"timezone":"Asia/Shanghai"},
	{"city":"Seoul",
		"population":9500000,
		"continent":"Asia",
		"country":"South Korea",
		"known_for":["technology",
			"K-pop",
			"palaces"],
		"coordinates":{"lat":37.5665,
			"long":126.978},
		"timezone":"Asia/Seoul"},
	{"city":"New Delhi",
		"population":32900000,
		"continent":"Asia",
		"country":"India",
		"known_for":["government",
			"historic monuments",
			"markets"],
		"coordinates":{"lat":28.6139,
			"long":77.209},
		"timezone":"Asia/Kolkata"},
	{"city":"Bangkok",
		"population":10539000,
		"continent":"Asia",
		"country":"Thailand",
		"known_for":["temples",
			"street food",
			"nightlife"],
		"coordinates":{"lat":13.7563,
			"long":100.5018},
		"timezone":"Asia/Bangkok"},
	{"city":"Jakarta",
		"population":10562000,
		"continent":"Asia",
		"country":"Indonesia",
		"known_for":["megacity",
			"commerce",
			"government"],
		"coordinates":{"lat":-6.2088,
			"long":106.8456},
		"timezone":"Asia/Jakarta"},
	{"city":"Cairo",
		"population":10230000,
		"continent":"Africa",
		"country":"Egypt",
		"known_for":["pyramids proximity",
			"Nile",
			"history"],
		"coordinates":{"lat":30.0444,
			"long":31.2357},
		"timezone":"Africa/Cairo"},
	{"city":"Nairobi",
		"population":4397000,
		"continent":"Africa",
		"country":"Kenya",
		"known_for":["safari gateway",
			"business",
			"national park"],
		"coordinates":{"lat":-1.2921,
			"long":36.8219},
		"timezone":"Africa/Nairobi"},
	{"city":"Abuja",
		"population":3770000,
		"continent":"Africa",
		"country":"Nigeria",
		"known_for":["planned capital",
			"government",
			"modern infrastructure"],
		"coordinates":{"lat":9.0765,
			"long":7.3986},
		"timezone":"Africa/Lagos"},
	{"city":"Canberra",
		"population":462000,
		"continent":"Oceania",
		"country":"Australia",
		"known_for":["planned city",
			"Parliament House",
			"museums"],
		"coordinates":{"lat":-35.2809,
			"long":149.13},
		"timezone":"Australia/Sydney"},
	{"city":"Wellington",
		"population":215000,
		"continent":"Oceania",
		"country":"New Zealand",
		"known_for":["harbor",
			"film industry",
			"government"],
		"coordinates":{"lat":-41.2865,
			"long":174.7762},
		"timezone":"Pacific/Auckland"}]);
